
services:
  db:
    image: postgres:16.9
    tty: true
    environment:
      POSTGRES_DB: tasksDB
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data


volumes:
  pgdata:
